- extensions:
  - default: false
  - name: OverloadedStrings

- flags:
  - default: false

- group:
    name: dollar
    enabled: true

- group:
    name: generalise
    enabled: true

- ignore:
    name: Use <$>

- ignore:
    name: Use bimap

- ignore:
    name: Use first
