version: '3.7'
services:

  aws:
    build:
      context: docker
      dockerfile: aws.Dockerfile
    command: sh -c 'aws --version && exec tail -f /dev/null'
    environment:
      AWS_ACCESS_KEY_ID: null
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: null
    init: true
    volumes:
      - $PWD:$PWD
    working_dir: $PWD

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:11.6
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  stack:
    build:
      context: docker
      dockerfile: stack.Dockerfile
    command: sh -c 'stack --version && exec tail -f /dev/null'
    environment:
      monadoc_client_id: 235ce8c873f4ed90905c
      monadoc_client_secret: null
      monadoc_commit: 4837a4e547171997cb289f2e523d79edb602fc71
      monadoc_port: 8080
      monadoc_url: http://localhost:8080
      PGDATABASE: postgres
      PGHOST: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGUSER: postgres
      STACK_ROOT: $PWD/.stack/root
      STACK_WORK: .stack/work
    init: true
    ports:
      - 8080:8080
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
