version: '3.7'
services:

  aws:
    build:
      context: docker
      dockerfile: aws.docker
    command: sh -c 'aws --version && exec tail -f /dev/null'
    environment:
      AWS_ACCESS_KEY_ID: null
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: null
    init: true
    volumes:
      - $PWD:$PWD
    working_dir: $PWD

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:11.6
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  stack:
    build:
      context: docker
      dockerfile: stack.docker
    command: sh -c 'stack --version && exec tail -f /dev/null'
    environment:
      PGDATABASE: postgres
      PGHOST: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGUSER: postgres
      STACK_ROOT: $PWD/.stack/root
      STACK_WORK: .stack/work
    init: true
    ports:
      - 8080
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
